packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: false
  prisma: true
  unrs-resolver: false

catalog:
  '@prisma/adapter-pg': 7.10.0
  '@prisma/client': 7.10.0
  '@types/node': ^26.6.2
  dotenv: ^18.0.3
  eslint: 10.9.1
  prisma: 7.10.0
  tsx: ^4.23.15
  typescript: 7.0.2
