import type { Metadata } from "next";
import { Sniglet } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toast";

const sniglet = Sniglet({
  variable: "--font-sniglet",
  weight: ["400", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${sniglet.variable} ${sniglet.className} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-[radial-gradient(circle,rgba(255,255,255,0.16)_1.2px,transparent_1.2px)] bg-size-[40px_40px]">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
